# Generated by Django 4.0.1 on 2022-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(related_name='category', through='news.PostCategory', to='news.Category', verbose_name='Категория'),
        ),
    ]
